package com.liziyuan.hope.log.manager.das.mapper;

import com.liziyuan.hope.log.manager.das.entity.UserOperateLog;
import com.liziyuan.hope.log.manager.das.entity.UserOperateLogPageExample;
import com.liziyuan.hope.log.manager.das.entity.UserOperateLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    long countByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    long countByPageExample(UserOperateLogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    int deleteByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    int insert(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    int insertSelective(UserOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    List<UserOperateLog> selectByExample(UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    List<UserOperateLog> selectByPage(UserOperateLogPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserOperateLog record, @Param("example") UserOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operate_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserOperateLog record, @Param("example") UserOperateLogExample example);
}