package com.liziyuan.hope.log.manager.das.entity;

import java.util.Date;

public class UserOperateLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.user_account
     *
     * @mbg.generated
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.sys_model_id
     *
     * @mbg.generated
     */
    private Long sysModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.sys_model_type
     *
     * @mbg.generated
     */
    private String sysModelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.operate_time
     *
     * @mbg.generated
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.operate_type_id
     *
     * @mbg.generated
     */
    private Long operateTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.operate_type
     *
     * @mbg.generated
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.operate_object
     *
     * @mbg.generated
     */
    private String operateObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.request_url
     *
     * @mbg.generated
     */
    private String requestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.request_type
     *
     * @mbg.generated
     */
    private String requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.request_method
     *
     * @mbg.generated
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.request_params
     *
     * @mbg.generated
     */
    private String requestParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operate_log.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.id
     *
     * @return the value of user_operate_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.id
     *
     * @param id the value for user_operate_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.user_id
     *
     * @return the value of user_operate_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.user_id
     *
     * @param userId the value for user_operate_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.user_account
     *
     * @return the value of user_operate_log.user_account
     *
     * @mbg.generated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.user_account
     *
     * @param userAccount the value for user_operate_log.user_account
     *
     * @mbg.generated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.user_name
     *
     * @return the value of user_operate_log.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.user_name
     *
     * @param userName the value for user_operate_log.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.sys_model_id
     *
     * @return the value of user_operate_log.sys_model_id
     *
     * @mbg.generated
     */
    public Long getSysModelId() {
        return sysModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.sys_model_id
     *
     * @param sysModelId the value for user_operate_log.sys_model_id
     *
     * @mbg.generated
     */
    public void setSysModelId(Long sysModelId) {
        this.sysModelId = sysModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.sys_model_type
     *
     * @return the value of user_operate_log.sys_model_type
     *
     * @mbg.generated
     */
    public String getSysModelType() {
        return sysModelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.sys_model_type
     *
     * @param sysModelType the value for user_operate_log.sys_model_type
     *
     * @mbg.generated
     */
    public void setSysModelType(String sysModelType) {
        this.sysModelType = sysModelType == null ? null : sysModelType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.operate_time
     *
     * @return the value of user_operate_log.operate_time
     *
     * @mbg.generated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.operate_time
     *
     * @param operateTime the value for user_operate_log.operate_time
     *
     * @mbg.generated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.operate_type_id
     *
     * @return the value of user_operate_log.operate_type_id
     *
     * @mbg.generated
     */
    public Long getOperateTypeId() {
        return operateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.operate_type_id
     *
     * @param operateTypeId the value for user_operate_log.operate_type_id
     *
     * @mbg.generated
     */
    public void setOperateTypeId(Long operateTypeId) {
        this.operateTypeId = operateTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.operate_type
     *
     * @return the value of user_operate_log.operate_type
     *
     * @mbg.generated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.operate_type
     *
     * @param operateType the value for user_operate_log.operate_type
     *
     * @mbg.generated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.operate_object
     *
     * @return the value of user_operate_log.operate_object
     *
     * @mbg.generated
     */
    public String getOperateObject() {
        return operateObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.operate_object
     *
     * @param operateObject the value for user_operate_log.operate_object
     *
     * @mbg.generated
     */
    public void setOperateObject(String operateObject) {
        this.operateObject = operateObject == null ? null : operateObject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.request_url
     *
     * @return the value of user_operate_log.request_url
     *
     * @mbg.generated
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.request_url
     *
     * @param requestUrl the value for user_operate_log.request_url
     *
     * @mbg.generated
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.request_type
     *
     * @return the value of user_operate_log.request_type
     *
     * @mbg.generated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.request_type
     *
     * @param requestType the value for user_operate_log.request_type
     *
     * @mbg.generated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.request_method
     *
     * @return the value of user_operate_log.request_method
     *
     * @mbg.generated
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.request_method
     *
     * @param requestMethod the value for user_operate_log.request_method
     *
     * @mbg.generated
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.request_params
     *
     * @return the value of user_operate_log.request_params
     *
     * @mbg.generated
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.request_params
     *
     * @param requestParams the value for user_operate_log.request_params
     *
     * @mbg.generated
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams == null ? null : requestParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.remark
     *
     * @return the value of user_operate_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.remark
     *
     * @param remark the value for user_operate_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operate_log.insert_time
     *
     * @return the value of user_operate_log.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operate_log.insert_time
     *
     * @param insertTime the value for user_operate_log.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}